#!/bin/bash

echo "======================================================="
echo "LocalShare - Step-by-Step Testing Instructions"
echo "======================================================="
echo ""
echo "IMPORTANT: Follow these steps EXACTLY"
echo ""
echo "You should have TWO terminal windows open."
echo ""
echo "------------------------------------------------------"
echo "TERMINAL 1 (Receiver):"
echo "------------------------------------------------------"
echo "1. Run: ./run.sh"
echo "2. In the GUI window that opens, click 'Start Receiving'"
echo "3. Watch the status log - you should see:"
echo "   - 'Receiving mode started...'"
echo "   - 'TCP Server listening on port 5000'"
echo "   - 'Broadcasting presence every 2000ms on UDP port 8888'"
echo "   - 'DEBUG: Sent PRESENCE: LOCALSHARE_PRESENCE:192.168.x.x:5000'"
echo ""
echo "------------------------------------------------------"
echo "TERMINAL 2 (Sender - THIS TERMINAL):"
echo "------------------------------------------------------"
echo "1. Make sure Terminal 1 is broadcasting (see messages above)"
echo "2. Run: ./run.sh"
echo "3. In the GUI window that opens, click 'Send File'"
echo "4. Wait 3 seconds for discovery"
echo "5. You should see a dialog with discovered receivers"
echo "6. Select the receiver and choose a test file"
echo ""
echo "------------------------------------------------------"
echo "Troubleshooting:"
echo "------------------------------------------------------"
echo "If NO receivers found:"
echo "  - Check that Terminal 1 shows 'DEBUG: Sent PRESENCE' messages"
echo "  - Check that both applications are running"
echo "  - Try closing both and starting again"
echo "  - Run: java -cp bin NetworkDiagnostic"
echo ""
echo "Press Enter to start LocalShare as SENDER..."
read

./run.sh
